# Generated by Django 5.2.16 on 2026-07-26 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('ticket_count', models.PositiveIntegerField(default=0)),
                ('date_range_start', models.DateTimeField(blank=True, null=True)),
                ('date_range_end', models.DateTimeField(blank=True, null=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hesk_row_id', models.PositiveIntegerField(blank=True, null=True)),
                ('tracking_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('requester_name', models.CharField(blank=True, max_length=255)),
                ('requester_email', models.CharField(blank=True, max_length=255)),
                ('followers', models.CharField(blank=True, max_length=500)),
                ('category_raw', models.CharField(blank=True, max_length=255)),
                ('stage', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Nivel 1', 'Nivel 1'), ('Nivel 2', 'Nivel 2'), ('Pre-Cierre', 'Pre-Cierre'), ('Cerrado', 'Cerrado'), ('Otro', 'Otro')], default='Otro', max_length=20)),
                ('request_type', models.CharField(blank=True, max_length=50)),
                ('area_categoria', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(blank=True, choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=20)),
                ('status', models.CharField(blank=True, choices=[('Nuevo', 'Nuevo'), ('Respondido', 'Respondido'), ('En progreso', 'En progreso'), ('Esperando respuesta', 'Esperando respuesta'), ('En espera', 'En espera'), ('Resuelto', 'Resuelto')], max_length=30)),
                ('owner_raw', models.CharField(blank=True, max_length=255)),
                ('team_code', models.CharField(blank=True, default='(sin asignar)', max_length=30)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('message', models.TextField(blank=True)),
                ('replies_count', models.PositiveIntegerField(default=0)),
                ('team_replies_count', models.PositiveIntegerField(default=0)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('related_ticket', models.CharField(blank=True, max_length=100)),
                ('history_raw', models.TextField(blank=True)),
                ('ticket_url', models.URLField(blank=True, max_length=500)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.importbatch')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['batch', 'status'], name='tickets_tic_batch_i_bff690_idx'), models.Index(fields=['batch', 'team_code'], name='tickets_tic_batch_i_f2077c_idx'), models.Index(fields=['created_at'], name='tickets_tic_created_5dd600_idx')],
                'constraints': [models.UniqueConstraint(fields=('batch', 'tracking_id'), name='unique_ticket_per_batch')],
            },
        ),
    ]
