# Generated by Django 5.2.16 on 2026-07-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamArea',
            fields=[
                ('team_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('area_type', models.CharField(choices=[('pais', 'Soporte local (país)'), ('funcional', 'Área funcional / corporativa')], default='funcional', max_length=20)),
            ],
            options={
                'verbose_name': 'Área / país de equipo',
                'verbose_name_plural': 'Áreas / países de equipos',
                'ordering': ['area_type', 'display_name'],
            },
        ),
    ]
