# Generated by Django 5.2.16 on 2026-07-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_teamarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamarea',
            name='area_type',
            field=models.CharField(choices=[('pais', 'Soporte local (país / unidad de negocio)'), ('funcional', 'Área funcional / corporativa')], default='funcional', max_length=20),
        ),
    ]
