# Generated by Django 5.2.16 on 2026-07-26 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_seed_team_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='first_seen_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_nuevos', to='tickets.importbatch'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_actualizados', to='tickets.importbatch'),
        ),
    ]
