# Generated by Django 5.2.16 on 2026-07-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_copy_batch_to_seen_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_ticket_per_batch',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_batch_i_bff690_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_batch_i_f2077c_idx',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='batch',
        ),
        migrations.AddField(
            model_name='importbatch',
            name='new_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='unchanged_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='updated_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tracking_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='tickets_tic_status_0e5646_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['team_code'], name='tickets_tic_team_co_4c71f5_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['last_batch'], name='tickets_tic_last_ba_2c0935_idx'),
        ),
    ]
