# Generated by Django 5.2.16 on 2026-07-26 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_remove_ticket_unique_ticket_per_batch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jefes', to='tickets.teamarea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_gestionadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jefe de área',
                'verbose_name_plural': 'Jefes de área',
                'constraints': [models.UniqueConstraint(fields=('user', 'team_area'), name='unique_user_area_manager')],
            },
        ),
    ]
