# Generated by Django 5.2.16 on 2026-07-26 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_areamanager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='tickets.teamarea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_favoritas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Área de seguimiento',
                'verbose_name_plural': 'Áreas de seguimiento',
                'ordering': ['team_area__display_name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'team_area'), name='unique_user_area_favorita')],
            },
        ),
    ]
