# Generated by Django 5.2.16 on 2026-07-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_areafavorita'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seguimiento_notas',
            field=models.TextField(blank=True, default=''),
        ),
    ]
