# Generated by Django 5.2.16 on 2026-07-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticket_seguimiento_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resuelto_por_nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resuelto_por_team_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tiempo_resolucion_tecnico_segundos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['resuelto_por_team_code'], name='tickets_tic_resuelt_4b7267_idx'),
        ),
    ]
