# Generated by Django 5.2.16 on 2026-07-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_ticket_resuelto_por_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resuelto_por_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
